//
// Created by Leo on 29.04.2023.
//

#ifndef GDS1PORSCHEMUEHK_HEADER_H
#define GDS1PORSCHEMUEHK_HEADER_H

#define VERSION 1.0

#define LCD_BACKLIGHT_OFF_TIME 60


#define FACTORY_AXIS_COUNT 3
#define FACTORY_BUTTON_COUNT 5
#define FACTORY_JOYSTICK_MODE 0

#define FACTORY_AXIS_CALIBRATION_MIN 0
#define FACTORY_AXIS_CALIBRATION_MAX 4095
#define FACTORY_AXIS_CALIBRATION_CENTER 2048

#define FACTORY_AXIS_DIGITAL_CALIBRATION_LOWER 1365
#define FACTORY_AXIS_DIGITAL_CALIBRATION_UPPER 2730

#define FACTORY_AXIS_BASE 0.3

#define FACTORY_AXIS_MODE 0
#define FACTORY_AXIS_CALIBRATE_CENTER false


#define FACTORY_BUTTON_NORMAL_OPEN 1
#define FACTORY_BUTTON_TOGGLE_MODE 0

#define JOYSTICK_MIN_VALUE (-1028)
#define JOYSTICK_CENTER_VALUE 0
#define JOYSTICK_MAX_VALUE 1028





#define LCD_WIDTH 20
#define LCD_HEIGHT 4

#define ENCODER_CLK_PIN 6
#define ENCODER_DT_PIN 7
#define ENCODER_BUTTON_PIN 8
#define ENCODER_BUTTON_DEBOUNCE_TIME 150

#define EEPROM_ADDRESS 0b1010000
#define EEPROM_MAX_MEMORY_ADDRESS 0x1FFF
#define EEPROM_SDA_PIN 4
#define EEPROM_SCL_PIN 5

#define AD_CHANNEL_COUNT 8
#define AD_SPI_SCK 10
#define AD_SPI_MOSI 11
#define AD_SPI_MISO 12
#define AD_SPI_CS 14

#define BUTTON_MATRIX_ROWS 8
#define BUTTON_MATRIX_COLUMNS 3

#define BUTTON_DEMUX_E 20
#define BUTTON_DEMUX_S0 16
#define BUTTON_DEMUX_S1 17
#define BUTTON_DEMUX_S2 18

#define BUTTON_COLUMN_0 15
#define BUTTON_COLUMN_1 9
#define BUTTON_COLUMN_2 20

#define BUTTON_DEBOUNCE_TIME 50



#endif //GDS1PORSCHEMUEHK_HEADER_H
